language: python
python:
  - "3.5"
install:
  - pip install termcolor
  - pip install codecov
  - pip install coverage
script:
  - py.test
  - coverage run test_rpn.py
  - coverage report -m
after_success:
  - codecov

